server:
  port: 9000

# 数据源配置
spring:
  datasource:
    username: ENC(R1lpKAwWdqUS4HC4TjD0H9E3toJzLUmxUwY2KVXiQXuvlPDCot2aRFoVkXuBqNwR)
    password: ENC(B9f5M5jz1yAQ+2tnso6rUXf13/FKfNmkmEJ/w51JVYTXh/LLTJWC4coLHTUCyFMj)
    url: ENC(QXdErpD1aQbSOYnUpk9pHtrG4TQJY6DImtmAkF0zeNszwDlBL8DKEcWhQPrJkVG/Iks9ahhvGTQFdRSftMbCoFQLau0L3U5nc3uh8ftd7jbilMKL1MdrBVb09w8FaeffaijK86q23BiPma+2829wfw==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# fastdep-shiro-jwt配置
fastdep:
  shiro-jwt:
    filter:
      front:
        path: /front/**
        role: anon
      api:
        path: /api/v1/**
        role: jwt
    secret: 6Dx8SIuaHXJYnpsG18SSpjPs50lZcT52
    expireTime: 7200000 # token有效期
    prefix: ""  # token校验时的前缀
    signPrefix: "" # token生成签名的前缀
    header: "Authorization" # token校验时的header头

# 日志配置
logging:
  level:
    com.qraffa.easyrentboot.dao: DEBUG